# Here are some guides
#
# https://ymgblog.com/2018/04/30/396/
# https://npchk.info/linux-flexget-rss/
# https://linkthis.me/2018/02/15/the-note-of-using-flexget/
#
# https://github.com/Aniverse/WiKi/blob/master/Flexget.md
# https://github.com/Aniverse/WiKi/blob/master/How.to.use.RSS.md#flexget-rss
#
# For more usages, check the offical site: https://flexget.com

templates:
  freespace:
    free_space:
      path: /home/SCRIPTUSERNAME
      space: 10240
  qb:
    qbittorrent:
      path: /home/SCRIPTUSERNAME/qbittorrent/download/
      host: localhost
      port: 2017
      username: SCRIPTUSERNAME
      password: SCRIPTPASSWORD
  tr:
    transmission:
      path: /home/SCRIPTUSERNAME/transmission/download/
      host: localhost
      port: 9099
      username: SCRIPTUSERNAME
      password: SCRIPTPASSWORD
  de:
    deluge:
      path: /home/SCRIPTUSERNAME/deluge/download/
      host: localhost
      port: 58846
      username: SCRIPTUSERNAME
      password: SCRIPTPASSWORD
  size:
    content_size:
      min: 6000
      max: 666666
      strict: no
tasks:
  HDChina:
    rss: https://hdchina.org/torrentrss.php
    if:
      - "'HDChina' in title and '1080p' in title": accept
      - "'HDCTV' in title": accept
    template:
      - freespace
      - size
      - qb
    qbittorrent:
      label: HDChina
  MTeam:
    rss: https://tp.m-team.cc/torrentrss.php
    regexp:
      accept:
        - OneHD
      reject:
        - MTeamPAD
    template:
      - de
    content_size:
      min: 15000
      max: 100000
      strict: no
    deluge:
      maxupspeed: 12800.0
web_server:
  port: 6566
  web_ui: yes
# base_url: /flexget
schedules: no
